version: "2"

services:
  app:
    ports:
      - 8080:8080
    depends_on:
      - db
    build:
      context: .
      dockerfile: Application.Dockerfile
    volumes:
      - ./:/usr/src/app

  db:
    image: postgres
    ports:
      - 7878:5432
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
volumes:
  maven-repo:
