version: "2"
services:
  app:
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
      - ./.m2:/root/.m2
    depends_on:
      - db
    build:
      context: .
      dockerfile: Application.Dockerfile
    command: /bin/sh -c "unset MAVEN_CONFIG && ./mvnw spring-boot:run"
  db:
    image: postgres
    ports:
      - 7878:5432
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password